name: SystemShop
version: 1.0.3
main: com.holyw.wowah.SystemShop
api-version: 1.21
author: holyw
depend: [Vault]
softdepend: [Essentials, PlaceholderAPI]

commands: # Changed ah to shop
  shop:
    description: Opens the System Shop or performs admin commands.
    usage: /shop [sell/order/refill/purge/reload]

permissions:
  systemshop.admin:
    description: Allows access to admin commands like /shop purge.
    default: op